//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public string BankID { get; set; }
        public string BankName { get; set; }
        public string BankFullName { get; set; }
        public string BankAddress { get; set; }
        public string BankMan { get; set; }
        public string BankTel { get; set; }
        public decimal BankMoney { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<int> BankState { get; set; }
    }
}
