//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public Dept()
        {
            this.Emp = new HashSet<Emp>();
        }
    
        public int DID { get; set; }
        public string DName { get; set; }
        public int DParentID { get; set; }
        public bool DState { get; set; }
    
        public virtual ICollection<Emp> Emp { get; set; }
    }
}
