//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpJob { get; set; }
        public string EmpSex { get; set; }
        public Nullable<System.DateTime> EmpBday { get; set; }
        public string EmpTCType { get; set; }
        public Nullable<double> EmpTcRate { get; set; }
        public string EmpTel { get; set; }
        public string EmpMail { get; set; }
        public string EmpQQ { get; set; }
        public string EmpAddr { get; set; }
        public string EmpMark { get; set; }
        public Nullable<bool> IsSelect { get; set; }
        public int Did { get; set; }
        public int EmpState { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
