//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProID { get; set; }
        public Nullable<int> PTID { get; set; }
        public Nullable<int> PUID { get; set; }
        public Nullable<int> PCID { get; set; }
        public Nullable<int> PSID { get; set; }
        public string ProName { get; set; }
        public string ProJP { get; set; }
        public string ProTM { get; set; }
        public string ProWorkShop { get; set; }
        public Nullable<int> ProMax { get; set; }
        public Nullable<int> ProMin { get; set; }
        public Nullable<decimal> ProInPrice { get; set; }
        public Nullable<decimal> ProPrice { get; set; }
        public string ProDesc { get; set; }
        public Nullable<int> ProState { get; set; }
        public byte[] ProImg { get; set; }
    }
}
