//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduceInDepotDeteil
    {
        public int PIDDID { get; set; }
        public string ProID { get; set; }
        public string PIDID { get; set; }
        public Nullable<int> PIDDAmount { get; set; }
        public Nullable<decimal> PIDDPrice { get; set; }
        public string PIDDDesc { get; set; }
    }
}
