//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLend
    {
        public string PPID { get; set; }
        public string PPName { get; set; }
        public string PPCompany { get; set; }
        public string PPMan { get; set; }
        public string PPTel { get; set; }
        public string PPAddress { get; set; }
        public string PPFax { get; set; }
        public string PPEmail { get; set; }
        public string PPUrl { get; set; }
        public string PPBank { get; set; }
        public string PPGoods { get; set; }
        public string PPDesc { get; set; }
        public Nullable<int> PLID { get; set; }
        public Nullable<int> PPState { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
