//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSSEntities : DbContext
    {
        public PSSEntities()
            : base("name=PSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Bank { get; set; }
        public DbSet<CheckDepot> CheckDepot { get; set; }
        public DbSet<CheckDepotDetail> CheckDepotDetail { get; set; }
        public DbSet<Compose> Compose { get; set; }
        public DbSet<ComposeDetail> ComposeDetail { get; set; }
        public DbSet<CustomerLevel> CustomerLevel { get; set; }
        public DbSet<CustomerOrder> CustomerOrder { get; set; }
        public DbSet<CustomerOrderDetail> CustomerOrderDetail { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<CustomerTypes> CustomerTypes { get; set; }
        public DbSet<Depots> Depots { get; set; }
        public DbSet<DepotStock> DepotStock { get; set; }
        public DbSet<Dept> Dept { get; set; }
        public DbSet<DevolveDetail> DevolveDetail { get; set; }
        public DbSet<Devolves> Devolves { get; set; }
        public DbSet<Emp> Emp { get; set; }
        public DbSet<InOutDepot> InOutDepot { get; set; }
        public DbSet<InOutDepotDetail> InOutDepotDetail { get; set; }
        public DbSet<LostDetail> LostDetail { get; set; }
        public DbSet<Losts> Losts { get; set; }
        public DbSet<OtherInDepot> OtherInDepot { get; set; }
        public DbSet<OtherInDepotDetail> OtherInDepotDetail { get; set; }
        public DbSet<OtherOutDepot> OtherOutDepot { get; set; }
        public DbSet<OtherOutDepotDetail> OtherOutDepotDetail { get; set; }
        public DbSet<PayOffDetail> PayOffDetail { get; set; }
        public DbSet<PayOffs> PayOffs { get; set; }
        public DbSet<PopedomRole> PopedomRole { get; set; }
        public DbSet<Popedoms> Popedoms { get; set; }
        public DbSet<ProduceInDepot> ProduceInDepot { get; set; }
        public DbSet<ProduceInDepotDeteil> ProduceInDepotDeteil { get; set; }
        public DbSet<ProduceOutDepot> ProduceOutDepot { get; set; }
        public DbSet<ProduceOutDepotDetail> ProduceOutDepotDetail { get; set; }
        public DbSet<ProductColor> ProductColor { get; set; }
        public DbSet<ProductLend> ProductLend { get; set; }
        public DbSet<ProductLendTypes> ProductLendTypes { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ProductSpec> ProductSpec { get; set; }
        public DbSet<ProductTypes> ProductTypes { get; set; }
        public DbSet<ProductUnit> ProductUnit { get; set; }
        public DbSet<QuotePrice> QuotePrice { get; set; }
        public DbSet<QuotePriceDetail> QuotePriceDetail { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SaleDepot> SaleDepot { get; set; }
        public DbSet<SaleDepotDetail> SaleDepotDetail { get; set; }
        public DbSet<SaleReturn> SaleReturn { get; set; }
        public DbSet<SaleReturnDetail> SaleReturnDetail { get; set; }
        public DbSet<SplitDetail> SplitDetail { get; set; }
        public DbSet<Splits> Splits { get; set; }
        public DbSet<StockDetail> StockDetail { get; set; }
        public DbSet<StockInDepot> StockInDepot { get; set; }
        public DbSet<StockInDepotDetail> StockInDepotDetail { get; set; }
        public DbSet<StockOutDepot> StockOutDepot { get; set; }
        public DbSet<StockOutDepotDetail> StockOutDepotDetail { get; set; }
        public DbSet<Stocks> Stocks { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersRole> UsersRole { get; set; }
    }
}
