//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReturnDetail
    {
        public int SRDID { get; set; }
        public string SRID { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> SRDAmount { get; set; }
        public Nullable<decimal> SRDPrice { get; set; }
        public string SRDDesc { get; set; }
    }
}
