//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDepotDetail
    {
        public int SDDID { get; set; }
        public string SDID { get; set; }
        public string ProID { get; set; }
        public Nullable<decimal> SDDPrice { get; set; }
        public Nullable<int> SDDDiscount { get; set; }
        public Nullable<decimal> SDDDisPrice { get; set; }
        public string SDDDesc { get; set; }
        public Nullable<int> SDDAmount { get; set; }
    }
}
